### ISSUE TITLE
Consider changing the name of the first module from "preface"

### ISSUE THREAD

**Issue by jhackett1** [jhackett1/ddat-codelabs#3]
Preface is a bit jargon-y.

The module contains groundwork that supports the later modules - an extremely short crash-course in user-centred design, but isn't strictly part of the curriculum.

**Comment by MaxwellRiess** [comment]
I agree 'Preface' is a bit dry and not so action focused. Here are some suggestions.  

- Project foundation
- Getting started
- Getting ready
- Choose a project
- Prepare to code

**Comment by jhackett1** [comment]
I'm going to go with "Get started" and close this issue for now. We can open a new one later if user research shows people still have a problem with it.

Personally I suspect something like "choose a project" may perform better, but we will see!
