### ISSUE TITLE
Attaching images to lessons

### ISSUE THREAD

**Issue by MaxwellRiess** [jhackett1/ddat-codelabs#6]
Apologies, but would it be possible to get some more help on adding images to lessons?

Very happy with adding the markdown to the pages, but where are the resources themselves being stored?

This is an example of something I was looking to add to lesson 1.3 on dev tools:

![inspector magnifier](https://user-images.githubusercontent.com/8421799/43137588-0d8fd05c-8f44-11e8-8b28-db5c1207f944.png)

**Comment by jhackett1** [comment]
This should be added to the `/lessons` folder, ideally obeying the same naming convention as the others already in there.

You should be able to upload it to the folder using Github's "Upload file" function.

To keep load times down, it should be a .jpg or .svg. If a .jpg, compress it first using a tool like ImageOptim.
